//Tutte le costanti per identificare le actions

//Login const
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

//Register const
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

//Forgot const
export const FORGOT_USER_START = 'REGISTER_USER_START';
export const FORGOT_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const FORGOT_USER_FAIL = 'REGISTER_USER_FAIL';

//Task const
export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';

export const DOWNLOAD_TASK_DATA_START = 'DOWNLOAD_TASK_DATA_START';
export const DOWNLOAD_TASK_DATA_SUCCESS = 'DOWNLOAD_TASK_DATA_SUCCESS';
export const ACCEPT_TASK_START = 'ACCEPT_TASK_START';
export const ACCEPT_TASK_FAIL = 'ACCEPT_TASK_FAIL';
export const ACCEPT_TASK_SUCCESS = 'ACCEPT_TASK_SUCCESS';
export const SHOW_TASK_START = 'SHOW_TASK_START';
export const SHOW_TASK_SUCCESS = 'SHOW_TASK_SUCCESS';

//Task list const
export const DOWNLOAD_LIST_START = 'DOWNLOAD_LIST_START';
export const DOWNLOAD_LIST_SUCCESS = 'DOWNLOAD_LIST_SUCCESS';
export const DOWNLOAD_LIST_END = 'DOWNLOAD_LIST_END';

export const FILTER_LIST_START = 'FILTER_LIST_START';
export const FILTER_LIST_SUCCESS = 'FILTER_LIST_SUCCESS';
export const FILTER_LIST_FAIL = 'FILTER_LIST_FAIL';

export const FILTER_TODOLIST_START = 'FILTER_TODOLIST_START';
export const FILTER_TODOLIST_FAIL = 'FILTER_TODOLIST_FAIL';
export const FILTER_TODOLIST_SUCCESS = 'FILTER_TODOLIST_SUCCESS';

//Profile const
export const DOWNLOAD_USER_DATA_START='DOWNLOAD_USER_DATA_START';
export const DOWNLOAD_USER_DATA_SUCCESS='DOWNLOAD_USER_DATA_SUCCESS';

export const FEED_USER_START='FEED_USER_START';
export const FEED_USER_SUCCESS='FEED_USER_SUCCESS';

export const DOWNLOAD_USERSLIST_START = 'DOWNLOAD_USERSLIST_START';
export const DOWNLOAD_USERSLIST_SUCCESS = 'DOWNLOAD_USERSLIST_SUCCESS';
export const FEED_USER_FAIL = 'FEED_USER_FAIL';


